import React from 'react'
import '../Styles/FooterLinks.css'
import { FooterLinkCard } from './FooterLinkCard';


const FooterLinksData = [
    {
      title: "Mobiles",
      links: [
        "4G Mobiles",
        " Smartphones",
        " Samsung Mobiles",
        " Micromax Mobiles",
        " Lenovo Mobiles",
        " iPhones",
        " Vivo Mobiles",
        " Oppo Mobiles",
        " Intex Mobiles",
        " Asus Mobiles",
      ],
    },
    {
      title: "Mobiles Accessories",
      links: [
        "Mobile Covers ",
        " Leather Mobile Covers ",
        " Printed Back Covers ",
        " 10000mAh Power Banks ",
        " Ambrane Power Banks ",
        " Intex Power Banks ",
        " VR Headsets ",
        " Smart Watches ",
        " Smart Bands ",
        " Fitness Bands ",
        " Tempered Glass ",
        " Wall Chargers ",
        " Feature Phones ",
        " Bluetooth Devices",
      ],
    },
    {
      title: "Mobiles",
      links: [
        "4G Mobiles",
        " Smartphones",
        " Samsung Mobiles",
        " Micromax Mobiles",
        " Lenovo Mobiles",
        " iPhones",
        " Vivo Mobiles",
        " Oppo Mobiles",
        " Intex Mobiles",
        " Asus Mobiles",
      ],
    },
    {
      title: "Mobiles Accessories",
      links: [
        "Mobile Covers ",
        " Leather Mobile Covers ",
        " Printed Back Covers ",
        " 10000mAh Power Banks ",
        " Ambrane Power Banks ",
        " Intex Power Banks ",
        " VR Headsets ",
        " Smart Watches ",
        " Smart Bands ",
        " Fitness Bands ",
        " Tempered Glass ",
        " Wall Chargers ",
        " Feature Phones ",
        " Bluetooth Devices",
      ],
    },
    {
      title: "Mobiles",
      links: [
        "4G Mobiles",
        " Smartphones",
        " Samsung Mobiles",
        " Micromax Mobiles",
        " Lenovo Mobiles",
        " iPhones",
        " Vivo Mobiles",
        " Oppo Mobiles",
        " Intex Mobiles",
        " Asus Mobiles",
      ],
    },
    {
      title: "Mobiles Accessories",
      links: [
        "Mobile Covers ",
        " Leather Mobile Covers ",
        " Printed Back Covers ",
        " 10000mAh Power Banks ",
        " Ambrane Power Banks ",
        " Intex Power Banks ",
        " VR Headsets ",
        " Smart Watches ",
        " Smart Bands ",
        " Fitness Bands ",
        " Tempered Glass ",
        " Wall Chargers ",
        " Feature Phones ",
        " Bluetooth Devices",
      ],
    },
    {
      title: "Mobiles",
      links: [
        "4G Mobiles",
        " Smartphones",
        " Samsung Mobiles",
        " Micromax Mobiles",
        " Lenovo Mobiles",
        " iPhones",
        " Vivo Mobiles",
        " Oppo Mobiles",
        " Intex Mobiles",
        " Asus Mobiles",
      ],
    },
    {
      title: "Mobiles Accessories",
      links: [
        "Mobile Covers ",
        " Leather Mobile Covers ",
        " Printed Back Covers ",
        " 10000mAh Power Banks ",
        " Ambrane Power Banks ",
        " Intex Power Banks ",
        " VR Headsets ",
        " Smart Watches ",
        " Smart Bands ",
        " Fitness Bands ",
        " Tempered Glass ",
        " Wall Chargers ",
        " Feature Phones ",
        " Bluetooth Devices",
      ],
    },
    {
      title: "Mobiles",
      links: [
        "4G Mobiles",
        " Smartphones",
        " Samsung Mobiles",
        " Micromax Mobiles",
        " Lenovo Mobiles",
        " iPhones",
        " Vivo Mobiles",
        " Oppo Mobiles",
        " Intex Mobiles",
        " Asus Mobiles",
      ],
    },
    {
      title: "Mobiles Accessories",
      links: [
        "Mobile Covers ",
        " Leather Mobile Covers ",
        " Printed Back Covers ",
        " 10000mAh Power Banks ",
        " Ambrane Power Banks ",
        " Intex Power Banks ",
        " VR Headsets ",
        " Smart Watches ",
        " Smart Bands ",
        " Fitness Bands ",
        " Tempered Glass ",
        " Wall Chargers ",
        " Feature Phones ",
        " Bluetooth Devices",
      ],
    },
    {
      title: "Mobiles",
      links: [
        "4G Mobiles",
        " Smartphones",
        " Samsung Mobiles",
        " Micromax Mobiles",
        " Lenovo Mobiles",
        " iPhones",
        " Vivo Mobiles",
        " Oppo Mobiles",
        " Intex Mobiles",
        " Asus Mobiles",
      ],
    },
    {
      title: "Mobiles Accessories",
      links: [
        "Mobile Covers ",
        " Leather Mobile Covers ",
        " Printed Back Covers ",
        " 10000mAh Power Banks ",
        " Ambrane Power Banks ",
        " Intex Power Banks ",
        " VR Headsets ",
        " Smart Watches ",
        " Smart Bands ",
        " Fitness Bands ",
        " Tempered Glass ",
        " Wall Chargers ",
        " Feature Phones ",
        " Bluetooth Devices",
      ],
    },
    {
      title: "Mobiles",
      links: [
        "4G Mobiles",
        " Smartphones",
        " Samsung Mobiles",
        " Micromax Mobiles",
        " Lenovo Mobiles",
        " iPhones",
        " Vivo Mobiles",
        " Oppo Mobiles",
        " Intex Mobiles",
        " Asus Mobiles",
      ],
    },
    {
      title: "Mobiles Accessories",
      links: [
        "Mobile Covers ",
        " Leather Mobile Covers ",
        " Printed Back Covers ",
        " 10000mAh Power Banks ",
        " Ambrane Power Banks ",
        " Intex Power Banks ",
        " VR Headsets ",
        " Smart Watches ",
        " Smart Bands ",
        " Fitness Bands ",
        " Tempered Glass ",
        " Wall Chargers ",
        " Feature Phones ",
        " Bluetooth Devices",
      ],
    },
    {
      title: "Mobiles",
      links: [
        "4G Mobiles",
        " Smartphones",
        " Samsung Mobiles",
        " Micromax Mobiles",
        " Lenovo Mobiles",
        " iPhones",
        " Vivo Mobiles",
        " Oppo Mobiles",
        " Intex Mobiles",
        " Asus Mobiles",
      ],
    },
    {
      title: "Mobiles Accessories",
      links: [
        "Mobile Covers ",
        " Leather Mobile Covers ",
        " Printed Back Covers ",
        " 10000mAh Power Banks ",
        " Ambrane Power Banks ",
        " Intex Power Banks ",
        " VR Headsets ",
        " Smart Watches ",
        " Smart Bands ",
        " Fitness Bands ",
        " Tempered Glass ",
        " Wall Chargers ",
        " Feature Phones ",
        " Bluetooth Devices",
      ],
    },
    {
      title: "Mobiles",
      links: [
        "4G Mobiles",
        " Smartphones",
        " Samsung Mobiles",
        " Micromax Mobiles",
        " Lenovo Mobiles",
        " iPhones",
        " Vivo Mobiles",
        " Oppo Mobiles",
        " Intex Mobiles",
        " Asus Mobiles",
      ],
    },
  ];
export const FooterLinks = () => {
    return (
        <div className="Footer-links">
          <div className="Footer-links-container">
            {FooterLinksData.map((item, i) => {
              return <FooterLinkCard key={i} title={item.title} links={item.links} />;
            })}
          </div>
        </div>
      );
    };